name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ php.pem }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Deploy to EC2
      run: |
        ssh ubuntu@${{ 65.2.5.83 }} "cd /path/to/your/app && git pull origin main && docker-compose up -d"
